indigo-dc/tosca-types

- custom_types.yaml
The tosca.capabilities.indigo.Container.Application.Docker.Chronos capability must be declared in the capability section
> Bugfix: Chronos capability

- examples/indigo_job_output_upload_swift.yaml
- examples/indigo_job_output_upload_web.yaml
Fix examples according to custom-type definition
> Merge from Chronos

- artifacts/mesos/cms_mesos_master_install.yml
- artifacts/mesos/cms_mesos_slave_install.yml
- custom_types.yaml
This patch includes the definitions of new types to support CMS use-case
> Added new types for CMS use-case

- examples/web_mysql_tosca_across_clouds.yaml
> Use policy property instead of metadata to select SLA

- examples/web_mysql_tosca_across_clouds.yaml
The previous values where service_ids (see
http://indigo.cloud.plgrid.pl/slam/preferences/indigo-dc for details)
> Changed wrong sla_ids to valid ones

- examples/cellar_webapp_mem.yaml
The file name cellar-webapp-sql.tgz should be cellar-webapp-mem.tgz
> Fixed file named and included outputs section

- examples/cellar_webapp_mem_aws.yaml
- examples/kepler_aws.yaml
Included templates to deploy on AWS (sample application Cellar and Kepler).
> Included templates to deploy on AWS

- examples/galaxy_elastic_cluster_aws.yaml
Created template to deploy a Galaxy-based elastic cluster on AWS
> Created template to deploy a Galaxy elastic cluster on AWS

- custom_types.yaml
This PR aims to fix the problems encountered in deploying the Mesos template on AWS
> Fixing MesosMaster inputs for ansible role

- examples/mesos_cluster_aws.yaml
This PR aims at fixing issues faced when deploying the Mesos cluster on AWS
> Fixing network related variables for using private IPs

- examples/mesos_cluster_aws.yaml
TOSCA Template for Mesos cluster deployment on AWS
> Maricaantonacci patch aws

- custom_types.yaml
> add artifact to GalaxyShedTool type

- artifacts/galaxy/galaxy_tools_configure.yml
fix {{galaxy_flavor}} recipe address
> fix galaxy-flavor address

- artifacts/mesos/mesos_lb_install.yml
- artifacts/mesos/mesos_master_install.yml
- artifacts/mesos/mesos_slave_install.yml
- custom_types.yaml
- examples/mesos_cluster.yaml
- examples/mesos_elastic_cluster.yaml
The changes included in this PR allow to use the updated version of the ansible roles for deploying a Mesos cluster
> Maricaantonacci indigo 2

- examples/mesos_cluster.yaml
- examples/mesos_elastic_cluster.yaml
Fix the indigo_custom_types import URL after successfull tests execution of maricaantonacci-indigo-2 PR
> Restoring import from master

- custom_types.yaml
- examples/indigo_marathon_app.yaml
Added labels field in tosca.nodes.indigo.Container.Application.Docker
Updated example for Marathon application (renamed as examples/indigo_marathon_app.yaml)
> Updated Marathon app definition

- custom_types.yaml
Changed link to artifact implementation
> fix implementation for GalaxyReferenceData custom type

- custom_types.yaml
- examples/galaxy_tosca.yaml
Changed from mtangaro-galaxy-tools to master implementation and galaxy_tosca example
> switch implementations to master

- artifacts/galaxy/galaxy_redfata_configure.yml
fix variable name from reference_data to get_refdata
> fix var name

- artifacts/galaxy/galaxy_redfata_configure.yml
removing  galaxy_flavor and get_refdata
> fix artifact

- custom_types.yaml
- examples/galaxy_tosca.yaml
changed mtangaro-galaxy-tools to master
> switch to master

- artifacts/mesos/mesos_master_install.yml
- artifacts/mesos/mesos_slave_install.yml
- custom_types.yaml
* Added NFS setup in the Mesos cluster to support persistent storage
* Added health checks for the applications (redis, postgres, elasticsearch, etc.) deployed through Marathon on top of Mesos
> Major improvements for Dariah use-case

- custom_types.yaml
- add export_dir property to configure galaxy database path
- add refdata_dir property to configure galaxy reference data mount-point
> add refdata_dir and export_dir galaxy custom types property

- custom_types.yaml
- examples/galaxy_elastic_cluster_elixirIT.yaml
- examples/galaxy_elixirIT_fastconfig.yaml
- examples/galaxy_tosca.yaml
switched to master tosca template and custom types
> swithced to master

- artifacts/galaxy/galaxy_wn_configure.yml
- examples/galaxy_onedata_elixirIT.yaml
- fix wn configuration
- add galaxy template with onedata support
> fix wn configuration

- custom_types.yaml
- onedata client configuration
- CMS WN stagein configuration
> add wn support for onedata stagein

- artifacts/galaxy/galaxy_wn_configure.yml
- custom_types.yaml
- examples/galaxy_elastic_cluster.yaml
- examples/galaxy_elixirIT_fastconfig.yaml
- pass as input the galaxy ip to wn
- fix fastconfig type in tosca template
> galaxy wn configuration

- artifacts/galaxy/galaxy_tools_configure.yml
- custom_types.yaml
- examples/galaxy_elastic_cluster_elixirIT.yaml
- examples/galaxy_onedata_elixirIT.yaml
- examples/galaxy_tosca.yaml
1. add galaxy version to tools artifact
2. update related templates
> add galaxy version to tools artifact

- artifacts/galaxy/galaxy_install.yml
- artifacts/galaxy/galaxy_os_install.yml
- custom_types.yaml
1. add nfs role to GalaxyPortal, GalaxyPortalAndStorage and GalaxyFastConfig
2. removed properties from GalaxyFastConfig, since it is derived from GalaxyPortalAndStorage and all of them are there.
> add nfs role

- artifacts/galaxy/galaxy_tools_configure.yml
- custom_types.yaml
- examples/galaxy_cluster.yaml
- examples/galaxy_cluster_elixirIT.yaml
- examples/galaxy_elastic_cluster_full_elixirIT.yaml
- add galaxy elastic cluster (used for the review).
- add galaxy cluster (non elastic).
- reworked role for tools (artifact and custom-type fix)
> add galaxy elastic cluster recipe with encryption

- artifacts/galaxy/galaxy_fastconfig.yml
- custom_types.yaml
reworked ansible role, removed no more needed options.
> reworked fastconfig role

- artifacts/galaxy/galaxy_fastconfig.yml
- artifacts/galaxy/galaxy_install.yml
- artifacts/galaxy/galaxy_os_install.yml
- artifacts/galaxy/galaxy_redfata_configure.yml
- artifacts/galaxy/galaxy_tools_configure.yml
- artifacts/galaxy/galaxy_wn_configure_cvmfs.yml
- artifacts/galaxy/galaxy_wn_configure_tooldeps.yml
- custom_types.yaml
galaxy-no-tools and galaxy-minimal are the same.
Start working to fastconfig to configure elastic cluster.
> Allow galaxy_flavor value: galaxy-minimal

- artifacts/ga4gh_cloud_apis/tesk_install.yml
- custom_types.yaml
Add TESK for ELIXIR GA4GH Cloud APIs: https://github.com/EMBL-EBI-TSI/TESK
> Ga4gh cloud apis

- custom_types.yaml
- examples/qcg-job.yaml
Improve QCG type and add example template for DEEP
> Qcg integration

- artifacts/os/configure_users.yml
- artifacts/zabbix/zabbix_agent_install.yml
- custom_types.yaml
- remove tosca.nodes.indigo.MonitoredCompute
- modify tosca.nodes.indigo.Compute in order to include additional properties (e.g. os_users)
- add new tosca.nodes.indigo.ZabbixAgent (SoftwareComponent) to install zabbix agent on host
> Reorganize Compute node types
